Work with tar's bootstrap.
* gnulib-tool (func_emit_initmacro_end): Use m4_defn in the case
where LIBSOURCES_DIR contains .#bootmp but must not be treated as
an m4 comment.

Signed-off-by: Eric Blake <ebb9@byu.net>

diff --git a/gnulib-tool b/gnulib-tool
--- a/gnulib-tool
+++ b/gnulib-tool
@@ -2068,10 +2068,10 @@ func_emit_initmacro_end ()
   # the configure.ac resides; if it is run from a different directory, the
   # check is skipped.
   echo "  m4_ifval(${macro_prefix_arg}_LIBSOURCES_LIST, ["
-  echo "    m4_syscmd([test ! -d ]${macro_prefix_arg}_LIBSOURCES_DIR[ ||"
+  echo "    m4_syscmd([test ! -d ]m4_defn([${macro_prefix_arg}_LIBSOURCES_DIR])[ ||"
   echo "      for gl_file in ]${macro_prefix_arg}_LIBSOURCES_LIST[ ; do"
-  echo "        if test ! -r ]${macro_prefix_arg}_LIBSOURCES_DIR[/\$gl_file ; then"
-  echo "          echo \"missing file ]${macro_prefix_arg}_LIBSOURCES_DIR[/\$gl_file\" >&2"
+  echo "        if test ! -r ]m4_defn([${macro_prefix_arg}_LIBSOURCES_DIR])[/\$gl_file ; then"
+  echo "          echo \"missing file ]m4_defn([${macro_prefix_arg}_LIBSOURCES_DIR])[/\$gl_file\" >&2"
   echo "          exit 1"
   echo "        fi"
   echo "      done])dnl"
