javaexec-script: Remove support for 'gij'.
* build-aux/javaexec.sh.in: Don't test HAVE_GIJ.
* m4/javaexec.m4 (gt_JAVAEXEC): Don't set HAVE_GIJ. Don't set CONF_JAVA
to 'gij'.
* m4/javacomp.m4: Update comment.

diff --git a/build-aux/javaexec.sh.in b/build-aux/javaexec.sh.in
--- a/build-aux/javaexec.sh.in
+++ b/build-aux/javaexec.sh.in
@@ -41,24 +41,18 @@ if test -n "@HAVE_JAVA_ENVVAR@"; then
 else
   unset JAVA_HOME
   export CLASSPATH
-  if test -n "@HAVE_GIJ@"; then
-    # In this case, $CONF_JAVA is "gij".
+  if test -n "@HAVE_JAVA@"; then
+    # In this case, $CONF_JAVA is "java".
     test -z "$JAVA_VERBOSE" || echo "$CONF_JAVA $@"
     exec $CONF_JAVA "$@"
   else
-    if test -n "@HAVE_JAVA@"; then
-      # In this case, $CONF_JAVA is "java".
+    if test -n "@HAVE_JRE@"; then
+      # In this case, $CONF_JAVA is "jre".
       test -z "$JAVA_VERBOSE" || echo "$CONF_JAVA $@"
       exec $CONF_JAVA "$@"
     else
-      if test -n "@HAVE_JRE@"; then
-        # In this case, $CONF_JAVA is "jre".
-        test -z "$JAVA_VERBOSE" || echo "$CONF_JAVA $@"
-        exec $CONF_JAVA "$@"
-      else
-        echo 'Java virtual machine not found, try installing gij or set $JAVA, then reconfigure' 1>&2
-        exit 1
-      fi
+      echo 'Java virtual machine not found, try setting $JAVA, then reconfigure' 1>&2
+      exit 1
     fi
   fi
 fi
