javacomp-script: Remove support for 'gcj'.
* build-aux/javacomp.sh.in: Don't test HAVE_GCJ_C.
* m4/javacomp.m4 (gt_JAVACOMP): Don't set HAVE_GCJ_C. Don't test whether
$JAVAC is gcj. Don't set CONF_JAVAC to 'gcj -C'. Update comment.
(gt_JAVACOMP_DISABLED): Don't set HAVE_GCJ_C.

diff --git a/build-aux/javacomp.sh.in b/build-aux/javacomp.sh.in
--- a/build-aux/javacomp.sh.in
+++ b/build-aux/javacomp.sh.in
@@ -41,35 +41,27 @@ if test -n "@HAVE_JAVAC_ENVVAR@"; then
   exec $CONF_JAVAC "$@"
 else
   unset JAVA_HOME
-  if test -n "@HAVE_GCJ_C@"; then
-    # In this case, $CONF_JAVAC starts with "gcj -C".
+  if test -n "@HAVE_JAVAC@"; then
+    # In this case, $CONF_JAVAC starts with "javac".
     CLASSPATH="$CLASSPATH"
     export CLASSPATH
     test -z "$JAVA_VERBOSE" || echo "$CONF_JAVAC $@"
     exec $CONF_JAVAC "$@"
   else
-    if test -n "@HAVE_JAVAC@"; then
-      # In this case, $CONF_JAVAC starts with "javac".
-      CLASSPATH="$CLASSPATH"
+    if test -n "@HAVE_JIKES@"; then
+      # In this case, $CONF_JAVAC starts with "jikes".
+      # Combine given CLASSPATH and configured CLASSPATH.
+      if test -n "$CLASSPATH"; then
+        CLASSPATH="$CLASSPATH${CONF_CLASSPATH:+@CLASSPATH_SEPARATOR@$CONF_CLASSPATH}"
+      else
+        CLASSPATH="$CONF_CLASSPATH"
+      fi
       export CLASSPATH
       test -z "$JAVA_VERBOSE" || echo "$CONF_JAVAC $@"
       exec $CONF_JAVAC "$@"
     else
-      if test -n "@HAVE_JIKES@"; then
-        # In this case, $CONF_JAVAC starts with "jikes".
-        # Combine given CLASSPATH and configured CLASSPATH.
-        if test -n "$CLASSPATH"; then
-          CLASSPATH="$CLASSPATH${CONF_CLASSPATH:+@CLASSPATH_SEPARATOR@$CONF_CLASSPATH}"
-        else
-          CLASSPATH="$CONF_CLASSPATH"
-        fi
-        export CLASSPATH
-        test -z "$JAVA_VERBOSE" || echo "$CONF_JAVAC $@"
-        exec $CONF_JAVAC "$@"
-      else
-        echo 'Java compiler not found, try installing gcj or set $JAVAC, then reconfigure' 1>&2
-        exit 1
-      fi
+      echo 'Java compiler not found, try setting $JAVAC, then reconfigure' 1>&2
+      exit 1
     fi
   fi
 fi
