javaexec-script: Remove support for 'jview'.
* build-aux/javaexec.sh.in: Don't test HAVE_JVIEW.
* m4/javaexec.m4 (gt_JAVAEXEC): Don't set HAVE_JVIEW. Don't set
CONF_JAVA to 'jview'.
(gt_JAVAEXEC_DISABLED): Don't set HAVE_JVIEW.
* m4/javacomp.m4: Update comment.

diff --git a/build-aux/javaexec.sh.in b/build-aux/javaexec.sh.in
--- a/build-aux/javaexec.sh.in
+++ b/build-aux/javaexec.sh.in
@@ -56,14 +56,8 @@ else
         test -z "$JAVA_VERBOSE" || echo "$CONF_JAVA $@"
         exec $CONF_JAVA "$@"
       else
-        if test -n "@HAVE_JVIEW@"; then
-          # In this case, $CONF_JAVA is "jview".
-          test -z "$JAVA_VERBOSE" || echo "$CONF_JAVA $@"
-          exec $CONF_JAVA "$@"
-        else
-          echo 'Java virtual machine not found, try installing gij or set $JAVA, then reconfigure' 1>&2
-          exit 1
-        fi
+        echo 'Java virtual machine not found, try installing gij or set $JAVA, then reconfigure' 1>&2
+        exit 1
       fi
     fi
   fi
