javacomp-script: Remove support for 'jikes'.
* build-aux/javacomp.sh.in: Don't test HAVE_JIKES.
* m4/javacomp.m4 (gt_JAVACOMP): Don't set HAVE_JIKES. Don't set
CONF_JAVAC to 'jikes'. Update comment.
(gt_JAVACOMP_DISABLED): Don't set HAVE_JIKES.

diff --git a/build-aux/javacomp.sh.in b/build-aux/javacomp.sh.in
--- a/build-aux/javacomp.sh.in
+++ b/build-aux/javacomp.sh.in
@@ -48,20 +48,7 @@ else
     test -z "$JAVA_VERBOSE" || echo "$CONF_JAVAC $@"
     exec $CONF_JAVAC "$@"
   else
-    if test -n "@HAVE_JIKES@"; then
-      # In this case, $CONF_JAVAC starts with "jikes".
-      # Combine given CLASSPATH and configured CLASSPATH.
-      if test -n "$CLASSPATH"; then
-        CLASSPATH="$CLASSPATH${CONF_CLASSPATH:+@CLASSPATH_SEPARATOR@$CONF_CLASSPATH}"
-      else
-        CLASSPATH="$CONF_CLASSPATH"
-      fi
-      export CLASSPATH
-      test -z "$JAVA_VERBOSE" || echo "$CONF_JAVAC $@"
-      exec $CONF_JAVAC "$@"
-    else
-      echo 'Java compiler not found, try setting $JAVAC, then reconfigure' 1>&2
-      exit 1
-    fi
+    echo 'Java compiler not found, try setting $JAVAC, then reconfigure' 1>&2
+    exit 1
   fi
 fi
